
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/STARTER-team02
owner: ucsb-cs156-s25
repo_name: STARTER-team02
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-f25","number":79,"title":"pc - replace s25 with f25 throughout repo","url":"https://github.com/ucsb-cs156-s25/STARTER-team02/pull/79"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-fixIntegration","number":78,"title":"Improving Integration Test Speed","url":"https://github.com/ucsb-cs156-s25/STARTER-team02/pull/78"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-mergableWorkflow60","number":77,"title":"Adding a Workflow for Status Check Enforcement","url":"https://github.com/ucsb-cs156-s25/STARTER-team02/pull/77"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam/testingverifcommits","number":74,"title":"test","url":"https://github.com/ucsb-cs156-s25/STARTER-team02/pull/74"}]
