name: 60-Workflow Status Check Enforcement

on:
  pull_request:

jobs:
  waitForWorkflows:
    name: Wait for workflows
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Wait for workflows
        id: wait
        uses: smartcontractkit/chainlink-github-actions/utils/wait-for-workflows@main
        with:
          max-timeout: "900"
          polling-interval: "30"
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DEBUG: "true"

  afterWait:
    name: after-wait
    needs: [waitForWorkflows]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check needs results
        env:
          prnumber: ${{ github.event.pull_request.id }}
        run: |
            results=$(gh pr checks $prnumber --json state --jq '.[] | select(.state == "FAILURE")')
            echo "$results"
            if [ -z "$results" ]; then
            exit 0;
            else
            exit 1;
            fi
